[package]
name = "tsutil"
version = "0.1.0"
edition = "2021"

[dependencies]
pretty_env_logger = "0.5.0"
tree-sitter = "0.22.6"
tree-sitter-python = "0.21.0"
tree-sitter-rust = "0.21.2"

[build-dependencies]
cc = "1.0"
